### ISSUE TITLE
Move this repository to a more accessible location

### ISSUE THREAD

**Issue by Geod24** [dlang/ddox#236]
As DDOX is quite important to the D ecosystem, I believe it should be easier for people to discover, contribute, and have merge rights. Having it in `dlang`, `dlang-community`, or `vibe-d` would be a step forward IMO. I give those options by order of preference, as `dub` depends on `ddox`, I think `dlang` is the best place, with `dlang-community` a close second.

Would that work for you @s-ludwig ?

**Comment by s-ludwig** [comment]
Would be no problem, as long as nobody goes crazy with breaking changes.

**Comment by Geod24** [comment]
Judging from other repositories, I don't think that'd be an issue.

**Comment by WebFreak001** [comment]
since you still own the source I don't think there will be a big problem, since github just redirects the old repo URLs (even release downloads) to the new one.

**Comment by Geod24** [comment]
Ping @s-ludwig

**Comment by s-ludwig** [comment]
Yeah, so what's the plan? To @dlang?

**Comment by Geod24** [comment]
Yes I think that's the right location. Do you have access or do you need me to do anything ?

**Comment by s-ludwig** [comment]
I think you'll have to accept the repo and add me back with permissions, as I don't have owner permissions for dlang itself. I'll invoke the transfer now, though.

**Comment by s-ludwig** [comment]
Scrap that, you need owner access to initiate the transfer, too. I've made you an admin for ddox instead.

**Comment by s-ludwig** [comment]
Now I just don't have access to the repository anymore.

**Comment by Geod24** [comment]
Should be fixed

**Comment by WebFreak001** [comment]
can be closed then?

**Comment by WebFreak001** [comment]
I saw dub had the old repository for syncing, I changed it to dlang/ddox now
